<?php

namespace AxytosKaufAufRechnungShopware5\Adapter\Common\UnifiedShopwareModel;

use Shopware\Models\Order\Order as ShopwareOrder;
use AxytosKaufAufRechnungShopware5\DataAbstractionLayer\OrderRepository as OldOrderRepository;

class OrderAttributes
{
    /**
     * @var \Shopware\Models\Order\Order
     */
    private $order;

    /**
     * @var \AxytosKaufAufRechnungShopware5\DataAbstractionLayer\OrderRepository
     */
    private $orderRepository;

    public function __construct(ShopwareOrder $order, OldOrderRepository $orderRepository)
    {
        $this->order = $order;
        $this->orderRepository = $orderRepository;
    }

    /**
     * @return void
     */
    public function persist()
    {
        $this->orderRepository->saveOrder($this->order);
    }

    /**
     * @return string
     */
    public function getAxytosKaufAufRechnungOrderState()
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        return strval($this->order->getAttribute()->getAxytosKaufAufRechnungOrderState());
    }

    /**
     * @param string $value
     * @return void
     */
    public function setAxytosKaufAufRechnungOrderState($value)
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        $this->order->getAttribute()->setAxytosKaufAufRechnungOrderState($value);
    }

    /**
     * @return string|null
     */
    public function getAxytosKaufAufRechnungOrderStateData()
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        return $this->order->getAttribute()->getAxytosKaufAufRechnungOrderStateData();
    }

    /**
     * @param string|null $value
     * @return void
     */
    public function setAxytosKaufAufRechnungOrderStateData($value)
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        $this->order->getAttribute()->setAxytosKaufAufRechnungOrderStateData($value);
    }

    /**
     * @return bool
     */
    public function getAxytosKaufAufRechnungHasShippingReported()
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        return boolval($this->order->getAttribute()->getAxytosKaufAufRechnungHasShippingReported());
    }

    /**
     * @param bool $value
     * @return void
     */
    public function setAxytosKaufAufRechnungHasShippingReported($value)
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        $this->order->getAttribute()->setAxytosKaufAufRechnungHasShippingReported($value);
    }

    /**
     * @return string
     */
    public function getAxytosKaufAufRechnungPrecheckResponse()
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        return strval($this->order->getAttribute()->getAxytosKaufAufRechnungPrecheckResponse());
    }

    /**
     * @param string $value
     * @return void
     */
    public function setAxytosKaufAufRechnungPrecheckResponse($value)
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        $this->order->getAttribute()->setAxytosKaufAufRechnungPrecheckResponse($value);
    }

    /**
     * @return string
     */
    public function getAxytosKaufAufRechnungReportedTrackingCode()
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        return strval($this->order->getAttribute()->getAxytosKaufAufRechnungReportedTrackingCode());
    }

    /**
     * @param string $value
     * @return void
     */
    public function setAxytosKaufAufRechnungReportedTrackingCode($value)
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        $this->order->getAttribute()->setAxytosKaufAufRechnungReportedTrackingCode($value);
    }

    /**
     * @return string
     */
    public function getAxytosKaufAufRechnungOrderBasketHash()
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        return strval($this->order->getAttribute()->getAxytosKaufAufRechnungOrderBasketHash());
    }

    /**
     * @param string $value
     * @return void
     */
    public function setAxytosKaufAufRechnungOrderBasketHash($value)
    {
        /** @phpstan-ignore-next-line because this method is generated by shopware */
        $this->order->getAttribute()->setAxytosKaufAufRechnungOrderBasketHash($value);
    }
}
