<?php

namespace AxytosKaufAufRechnungShopware5\DataAbstractionLayer;

use Axytos\ECommerce\Order\OrderCheckProcessStates;
use AxytosKaufAufRechnungShopware5\Paymentmethod\PaymentMethodOptions;
use Doctrine\ORM\EntityRepository;
use Shopware\Components\Model\ModelManager;
use Shopware\Models\Attribute\Order as AttributeOrder;
use Shopware\Models\Order\Order;
use Shopware\Models\Order\Status;
use Shopware\Models\Payment\Payment;

class OrderRepository
{
    /**
     * @param int $orderId
     * @return \Shopware\Models\Order\Order|null
     */
    public function findOrder($orderId)
    {
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);

        /** @var \Shopware\Models\Order\Repository */
        $orderRepository = $modelManager->getRepository(Order::class);

        return $orderRepository->find($orderId);
    }

    /**
     * @param \Shopware\Models\Order\Order $order
     * @param int $orderStatusCode
     * @return void
     */
    public function saveOrderStatus($order, $orderStatusCode)
    {
        $orderStatus = $this->findStatusModelByCode($orderStatusCode);

        $order->setOrderStatus($orderStatus);

        $this->saveOrder($order);
    }

    /**
     * @param \Shopware\Models\Order\Order $order
     * @param int $paymentStatusCode
     * @return void
     */
    public function savePaymentStatus($order, $paymentStatusCode)
    {
        $paymentStatus = $this->findStatusModelByCode($paymentStatusCode);

        $order->setPaymentStatus($paymentStatus);

        $this->saveOrder($order);
    }

    /**
     * @param \Shopware\Models\Order\Order $order
     * @param \AxytosKaufAufRechnungShopware5\Configuration\AfterCheckoutOrderStatus $afterCheckoutOrderStatus
     * @return void
     */
    public function saveAfterCheckoutOrderStatus($order, $afterCheckoutOrderStatus)
    {
        $this->saveOrderStatus($order, $afterCheckoutOrderStatus->getStatusCode());
    }

    /**
     * @param \Shopware\Models\Order\Order $order
     * @param \AxytosKaufAufRechnungShopware5\Configuration\AfterCheckoutPaymentStatus $afterCheckoutPaymentStatus
     * @return void
     */
    public function saveAfterCheckoutPaymentStatus($order, $afterCheckoutPaymentStatus)
    {
        $this->savePaymentStatus($order, $afterCheckoutPaymentStatus->getStatusCode());
    }

    /**
     * @param \Shopware\Models\Order\Order $order
     * @return void
     */
    public function saveOrder($order)
    {
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);

        $modelManager->persist($order);
        $modelManager->flush();
    }

    /**
     * @param int $statusCode
     * @return \Shopware\Models\Order\Status
     */
    private function findStatusModelByCode($statusCode)
    {
        $statusCode = (int) $statusCode;
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);

        /** @var EntityRepository */
        $statusRepository = $modelManager->getRepository(Status::class);

        /** @var Status */
        return $statusRepository->find($statusCode);
    }

    /**
     * @return \Shopware\Models\Order\Order[]
     */
    public function getOrdersToSync()
    {
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);

        $queryBuilder = $modelManager->createQueryBuilder();
        $query = $queryBuilder->select('o')
            ->from(Order::class, 'o')
            ->leftJoin(Payment::class, 'p', 'WITH', 'p.id = o.paymentId')
            ->leftJoin(AttributeOrder::class, 'oa', 'WITH', 'o.id = oa.orderId') // @phpstan-ignore-line because this class is generated by shopware
            ->orWhere('oa.axytosKaufAufRechnungHasCreateInvoiceReported = false')
            ->orWhere('oa.axytosKaufAufRechnungHasRefundReported = false')
            ->orWhere('oa.axytosKaufAufRechnungHasShippingReported = false')
            ->orWhere('oa.axytosKaufAufRechnungReportedTrackingCode != o.trackingCode')
            ->andWhere('oa.axytosKaufAufRechnungHasCancelReported = false')
            ->andWhere('oa.axytosKaufAufRechnungCheckProcessState = :confirmedState')
            ->andWhere('p.name = :paymentMethod')
            ->setParameter('paymentMethod', PaymentMethodOptions::NAME)
            ->setParameter('confirmedState', OrderCheckProcessStates::CONFIRMED)
            ->getQuery();

        /** @var Order[] */
        $orders = $query->execute();

        return $orders ;
    }

    /**
     * @return void
     */
    public function beginTransaction()
    {
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);
        $modelManager->beginTransaction();
    }

    /**
     * @return void
     */
    public function commitTransaction()
    {
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);

        if ($modelManager->isOpen()) {
            $modelManager->flush();
        }

        $modelManager->commit();
    }

    /**
     * @return void
     */
    public function rollbackTransaction()
    {
        /** @var ModelManager */
        $modelManager = Shopware()->Container()->get(ModelManager::class);
        $modelManager->close();
        $modelManager->rollback();
    }
}
