<?php

declare(strict_types=1);

namespace AxytosKaufAufRechnungShopware5\Configuration;

use Shopware\Models\Order\Status;

class AfterCheckoutPaymentStatus
{
    public const PAYMENT_STATE_PARTIALLY_INVOICED = 'PAYMENT_STATE_PARTIALLY_INVOICED';
    public const PAYMENT_STATE_COMPLETELY_INVOICED = 'PAYMENT_STATE_COMPLETELY_INVOICED';
    public const PAYMENT_STATE_PARTIALLY_PAID = 'PAYMENT_STATE_PARTIALLY_PAID';
    public const PAYMENT_STATE_COMPLETELY_PAID = 'PAYMENT_STATE_COMPLETELY_PAID';
    public const PAYMENT_STATE_1ST_REMINDER = 'PAYMENT_STATE_1ST_REMINDER';
    public const PAYMENT_STATE_2ND_REMINDER = 'PAYMENT_STATE_2ND_REMINDER';
    public const PAYMENT_STATE_3RD_REMINDER = 'PAYMENT_STATE_3RD_REMINDER';
    public const PAYMENT_STATE_ENCASHMENT = 'PAYMENT_STATE_ENCASHMENT';
    public const PAYMENT_STATE_OPEN = 'PAYMENT_STATE_OPEN';
    public const PAYMENT_STATE_RESERVED = 'PAYMENT_STATE_RESERVED';
    public const PAYMENT_STATE_DELAYED = 'PAYMENT_STATE_DELAYED';
    public const PAYMENT_STATE_RE_CREDITING = 'PAYMENT_STATE_RE_CREDITING';
    public const PAYMENT_STATE_REVIEW_NECESSARY = 'PAYMENT_STATE_REVIEW_NECESSARY';
    public const PAYMENT_STATE_NO_CREDIT_APPROVED = 'PAYMENT_STATE_NO_CREDIT_APPROVED';
    public const PAYMENT_STATE_THE_CREDIT_HAS_BEEN_PRELIMINARILY_ACCEPTED = 'PAYMENT_STATE_THE_CREDIT_HAS_BEEN_PRELIMINARILY_ACCEPTED';
    public const PAYMENT_STATE_THE_CREDIT_HAS_BEEN_ACCEPTED = 'PAYMENT_STATE_THE_CREDIT_HAS_BEEN_ACCEPTED';
    public const PAYMENT_STATE_THE_PAYMENT_HAS_BEEN_ORDERED = 'PAYMENT_STATE_THE_PAYMENT_HAS_BEEN_ORDERED';
    public const PAYMENT_STATE_A_TIME_EXTENSION_HAS_BEEN_REGISTERED = 'PAYMENT_STATE_A_TIME_EXTENSION_HAS_BEEN_REGISTERED';
    public const PAYMENT_STATE_THE_PROCESS_HAS_BEEN_CANCELLED = 'PAYMENT_STATE_THE_PROCESS_HAS_BEEN_CANCELLED';

    private static array $paymentStatusMapping = [
        self::PAYMENT_STATE_PARTIALLY_INVOICED => Status::PAYMENT_STATE_PARTIALLY_INVOICED,
        self::PAYMENT_STATE_COMPLETELY_INVOICED => Status::PAYMENT_STATE_COMPLETELY_INVOICED,
        self::PAYMENT_STATE_PARTIALLY_PAID => Status::PAYMENT_STATE_PARTIALLY_PAID,
        self::PAYMENT_STATE_COMPLETELY_PAID => Status::PAYMENT_STATE_COMPLETELY_PAID,
        self::PAYMENT_STATE_1ST_REMINDER => Status::PAYMENT_STATE_1ST_REMINDER,
        self::PAYMENT_STATE_2ND_REMINDER => Status::PAYMENT_STATE_2ND_REMINDER,
        self::PAYMENT_STATE_3RD_REMINDER => Status::PAYMENT_STATE_3RD_REMINDER,
        self::PAYMENT_STATE_ENCASHMENT => Status::PAYMENT_STATE_ENCASHMENT,
        self::PAYMENT_STATE_OPEN => Status::PAYMENT_STATE_OPEN,
        self::PAYMENT_STATE_RESERVED => Status::PAYMENT_STATE_RESERVED,
        self::PAYMENT_STATE_DELAYED => Status::PAYMENT_STATE_DELAYED,
        self::PAYMENT_STATE_RE_CREDITING => Status::PAYMENT_STATE_RE_CREDITING,
        self::PAYMENT_STATE_REVIEW_NECESSARY => Status::PAYMENT_STATE_REVIEW_NECESSARY,
        self::PAYMENT_STATE_NO_CREDIT_APPROVED => Status::PAYMENT_STATE_NO_CREDIT_APPROVED,
        self::PAYMENT_STATE_THE_CREDIT_HAS_BEEN_PRELIMINARILY_ACCEPTED => Status::PAYMENT_STATE_THE_CREDIT_HAS_BEEN_PRELIMINARILY_ACCEPTED,
        self::PAYMENT_STATE_THE_CREDIT_HAS_BEEN_ACCEPTED => Status::PAYMENT_STATE_THE_CREDIT_HAS_BEEN_ACCEPTED,
        self::PAYMENT_STATE_THE_PAYMENT_HAS_BEEN_ORDERED => Status::PAYMENT_STATE_THE_PAYMENT_HAS_BEEN_ORDERED,
        self::PAYMENT_STATE_A_TIME_EXTENSION_HAS_BEEN_REGISTERED => Status::PAYMENT_STATE_A_TIME_EXTENSION_HAS_BEEN_REGISTERED,
        self::PAYMENT_STATE_THE_PROCESS_HAS_BEEN_CANCELLED => Status::PAYMENT_STATE_THE_PROCESS_HAS_BEEN_CANCELLED,
    ];

    private string $value;

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function getStatusCode(): int
    {
        return self::$paymentStatusMapping[$this->value];
    }
}
